router_bgp:
  as: '65201'
  router_id: 192.168.221.3
  bgp_defaults:
  - no bgp default ipv4-unicast
  - distance bgp 20 200 200
  - graceful-restart restart-time 300
  - graceful-restart
  - maximum-paths 4 ecmp 4
  peer_groups:
    IPv4-UNDERLAY-PEERS:
      type: ipv4
      password: AQQvKeimxJu+uGQ/yYvv9w==
      maximum_routes: 12000
      send_community: all
    EVPN-OVERLAY-PEERS:
      type: evpn
      update_source: Loopback0
      bfd: true
      password: q+VNViP5i4rVjW1cxFv2wA==
      send_community: all
      maximum_routes: 0
      ebgp_multihop: 3
  address_family_ipv4:
    peer_groups:
      IPv4-UNDERLAY-PEERS:
        activate: true
      EVPN-OVERLAY-PEERS:
        activate: false
  redistribute_routes:
    connected:
      route_map: RM-CONN-2-BGP
  neighbors:
    172.31.220.0:
      peer_group: IPv4-UNDERLAY-PEERS
      remote_as: '65200'
      description: DC2-SPINE1_Ethernet1
    192.168.221.1:
      peer_group: EVPN-OVERLAY-PEERS
      description: DC2-SPINE1
      remote_as: '65200'
    10.254.0.0:
      remote_as: '65101'
      description: DC1-LEAF1B
      peer_group: IPv4-UNDERLAY-PEERS
    10.254.0.2:
      remote_as: '65101'
      description: DC1-LEAF1B
      peer_group: IPv4-UNDERLAY-PEERS
  address_family_evpn:
    peer_groups:
      EVPN-OVERLAY-PEERS:
        activate: true
  vrfs:
    Tenant_A_WEB_Zone:
      router_id: 192.168.221.3
      rd: 192.168.221.3:1002
      route_targets:
        import:
          evpn:
          - 1002:1002
          - 1001:1002
        export:
          evpn:
          - 1002:1002
          - 1001:1002
      redistribute_routes:
      - connected
  vlans:
    20:
      tenant: Tenant_A
      rd: 192.168.221.3:10020
      route_targets:
        both:
        - 10020:10020
      redistribute_routes:
      - learned
static_routes:
- vrf: MGMT
  destination_address_prefix: 0.0.0.0/0
  gateway: 10.31.100.1
service_routing_protocols_model: multi-agent
ip_routing: true
daemon_terminattr:
  cvaddrs:
  - 10.31.100.4:9910
  cvauth:
    method: token
    key: null
    token_file: /tmp/token
  cvvrf: MGMT
  smashexcludes: ale,flexCounter,hardware,kni,pulse,strata
  ingestexclude: /Sysdb/cell/1/agent,/Sysdb/cell/2/agent
  disable_aaa: false
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
name_server:
  source:
    vrf: MGMT
  nodes:
  - 100.127.255.118
  - 8.8.8.8
spanning_tree:
  mode: mstp
  mst_instances:
    '0':
      priority: 16384
local_users:
  admin:
    privilege: 15
    role: network-admin
    sha512_password: $6$Df86J4/SFMDE3/1K$Hef4KstdoxNDaami37cBquTWOTplC.miMPjXVgQxMe92.e5wxlnXOLlebgPj8Fz1KO0za/RCO7ZIs4Q6Eiq1g1
  ansible:
    privilege: 15
    role: network-admin
    sha512_password: $6$Dzu11L7yp9j3nCM9$FSptxMPyIL555OMO.ldnjDXgwZmrfMYwHSr0uznE5Qoqvd9a6UdjiFcJUhGLtvXVZR1r.A/iF5aAt50hf/EK4/
  carlos:
    privilege: 15
    role: network-admin
    sha512_password: $6$Dzu11L7yp9j3nCM9$FSptxMPyIL555OMO.ldnjDXgwZmrfMYwHSr0uznE5Qoqvd9a6UdjiFcJUhGLtvXVZR1r.A/iF5aAt50hf/EK4/
  cvpadmin:
    privilege: 15
    role: network-admin
    sha512_password: $6$rZKcbIZ7iWGAWTUM$TCgDn1KcavS0s.OV8lacMTUkxTByfzcGlFlYUWroxYuU7M/9bIodhRO7nXGzMweUxvbk8mJmQl8Bh44cRktUj.
vrfs:
  MGMT:
    ip_routing: false
  Tenant_A_WEB_Zone:
    tenant: Tenant_A
    ip_routing: true
management_interfaces:
  Management1:
    description: oob_management
    shutdown: false
    vrf: MGMT
    ip_address: 10.31.100.103/24
    gateway: 10.31.100.1
    type: oob
management_api_http:
  enable_vrfs:
    MGMT: null
  enable_https: true
  https_ssl_profile: SSL_PROF1
  default_services: true
ethernet_interfaces:
  Ethernet1:
    peer: DC2-SPINE1
    peer_interface: Ethernet1
    peer_type: spine
    description: P2P_LINK_TO_DC2-SPINE1_Ethernet1
    shutdown: false
    mtu: 1500
    type: routed
    ip_address: 172.31.220.1/31
  Ethernet5:
    peer: DC1-LEAF1B
    peer_interface: Ethernet5
    peer_type: l3leaf
    description: P2P_LINK_TO_DC1-LEAF1B_Ethernet5
    type: routed
    shutdown: false
    mtu: 1500
    ip_address: 10.254.0.1/31
  Ethernet6:
    peer: DC1-LEAF1B
    peer_interface: Ethernet6
    peer_type: l3leaf
    description: P2P_LINK_TO_DC1-LEAF1B_Ethernet6
    type: routed
    shutdown: false
    mtu: 1500
    ip_address: 10.254.0.3/31
  Ethernet8:
    peer: dc2-server01
    peer_interface: Eth0
    peer_type: server
    description: dc2-server01_Eth0
    type: switched
    shutdown: false
    mode: access
    vlans: '20'
loopback_interfaces:
  Loopback0:
    description: EVPN_Overlay_Peering
    shutdown: false
    ip_address: 192.168.221.3/32
  Loopback1:
    description: VTEP_VXLAN_Tunnel_Source
    shutdown: false
    ip_address: 192.168.222.3/32
  Loopback20:
    description: Tenant_A_WEB_Zone_VTEP_DIAGNOSTICS
    shutdown: false
    vrf: Tenant_A_WEB_Zone
    ip_address: 10.255.20.3/32
prefix_lists:
  PL-LOOPBACKS-EVPN-OVERLAY:
    sequence_numbers:
      10:
        action: permit 192.168.221.0/24 eq 32
      20:
        action: permit 192.168.222.0/24 eq 32
route_maps:
  RM-CONN-2-BGP:
    sequence_numbers:
      10:
        type: permit
        match:
        - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
router_bfd:
  multihop:
    interval: 7000
    min_rx: 7000
    multiplier: 6
vlans:
  20:
    tenant: Tenant_A
    name: Tenant_A_WEB_Zone
ip_igmp_snooping:
  globally_enabled: true
ip_virtual_router_mac_address: 00:1c:73:00:dc:01
vlan_interfaces:
  Vlan20:
    tenant: Tenant_A
    tags:
    - web
    description: Tenant_A_WEB_Zone
    shutdown: false
    ip_address_virtual: 10.1.20.1/24
    vrf: Tenant_A_WEB_Zone
vxlan_interface:
  Vxlan1:
    description: DC2-LEAF1A_VTEP
    vxlan:
      udp_port: 4789
      source_interface: Loopback1
      vlans:
        20:
          vni: 10020
      vrfs:
        Tenant_A_WEB_Zone:
          vni: 1002
virtual_source_nat_vrfs:
  Tenant_A_WEB_Zone:
    ip_address: 10.255.20.3
ntp:
  local_interface:
    name: Management1
    vrf: MGMT
  servers:
  - name: 0.nl.pool.ntp.org
    preferred: true
    vrf: MGMT
  - name: 1.nl.pool.ntp.org
    vrf: MGMT
management_security:
  ssl_profiles:
  - name: SSL_PROF1
    tls_versions: 1.2
    certificate:
      file: capi.pem
      key: capikey.pem
aaa_authorization:
  exec:
    default: local
