---
- name: Manage Arista EOS EVPN/VXLAN Configuration
  hosts: FABRIC
  connection: local
  gather_facts: false
  collections:
    - arista.avd
    - arista.cvp
  tasks:
    - name: 'reset local folders for output'
      tags: [build, generate]
      import_role:
        name: arista.avd.build_output_folders

    - name: generate intended variables
      tags: [build, generate]
      import_role:
        name: arista.avd.eos_designs

    - name: generate device intended config and documentation
      tags: [build, generate]
      import_role:
        name: eos_cli_config_gen

- name: Configuration deployment with CVP
  hosts: cv_server
  connection: local
  gather_facts: false
  collections:
    - arista.avd
    - arista.cvp
  tasks:
    - name: run CVP provisioning for DC1
      import_role:
        name: arista.avd.eos_config_deploy_cvp
      vars:
        container_root: 'DC1_FABRIC'
        configlets_prefix: 'DC1-AVD'
        device_filter: 'DC1'
        state: present
        cv_collection: v3
      tags:
         - deploy-via-cvp
         - deploy

    - name: run CVP provisioning for DC2
      import_role:
        name: arista.avd.eos_config_deploy_cvp
      vars:
        container_root: 'DC2_FABRIC'
        configlets_prefix: 'DC2-AVD'
        device_filter: 'DC2'
        state: present
        cv_collection: v3
      tags:
         - deploy-via-cvp
         - deploy

#tags can be used to exclude tasks.
#Example: ansible-playbook dc1-fabric-deploy.yml --skip-tags "deploy"
# that will skip the deploy labeled tasks, 
#which is handy to check syntax before deploying.