---

# Connected servers

servers:
  dc1-server01:
    rack: Rack-dc1A
    adapters:
      - type: nic
        server_ports: [Eth0]
        switch_ports: [Ethernet8]
        switches: [DC1-LEAF1A]
        profile: TENANT_A_v10

  dc1-server02:
    rack: Rack-dc1B
    adapters:
      - type: nic
        server_ports: [Eth1]
        switch_ports: [Ethernet8]
        switches: [DC1-LEAF1B]
        profile: TENANT_A_WEB_Zone

  dc1-server03:
    rack: Rack-dc1B
    adapters:
      - type: nic
        server_ports: [Eth1]
        switch_ports: [Ethernet5]
        switches: [DC1-LEAF1A]
        profile: TENANT_A_WEB_Zone


# Connected firewalls
firewalls:
  dc1-fw1:
    rack: Rack-dc1A
    adapters:
      # MLAG dual-homed connection 
      - endpoint_ports: [ eth0, eth1 ]
        switch_ports: [ Ethernet7, Ethernet7 ]
        switches: [ DC1-LEAF1A, DC1-LEAF1B ]
        profile: TENANT_A_FIREWALL
        port_channel:
          description: PortChannel
          mode: active

# Connected routers
#routers:
#  dc1-rtr1:
#    rack: Rack-dc1A
#    adapters:
#      - endpoint_ports: [ Ethernet1 ]
#        switch_ports: [ Ethernet7 ]
#        switches: [ DC1-LEAF1B ]
#        profile: ROUTER

