---
fabric_name: FABRIC

is_deploy: true

# Validation lab
# local users
local_users:
  admin:
    privilege: 15
    role: network-admin
    sha512_password: "$6$Df86J4/SFMDE3/1K$Hef4KstdoxNDaami37cBquTWOTplC.miMPjXVgQxMe92.e5wxlnXOLlebgPj8Fz1KO0za/RCO7ZIs4Q6Eiq1g1"

  cvpadmin:
    privilege: 15
    role: network-admin
    sha512_password: "$6$rZKcbIZ7iWGAWTUM$TCgDn1KcavS0s.OV8lacMTUkxTByfzcGlFlYUWroxYuU7M/9bIodhRO7nXGzMweUxvbk8mJmQl8Bh44cRktUj."

  ansible:
    privilege: 15
    role: network-admin
    sha512_password: "$6$Dzu11L7yp9j3nCM9$FSptxMPyIL555OMO.ldnjDXgwZmrfMYwHSr0uznE5Qoqvd9a6UdjiFcJUhGLtvXVZR1r.A/iF5aAt50hf/EK4/"

  carlos:
    privilege: 15
    role: network-admin
    sha512_password: "$6$Dzu11L7yp9j3nCM9$FSptxMPyIL555OMO.ldnjDXgwZmrfMYwHSr0uznE5Qoqvd9a6UdjiFcJUhGLtvXVZR1r.A/iF5aAt50hf/EK4/"


# Cloud Vision server information
cvp_instance_ip: 10.31.100.4
cvp_ingestauth_key: 'telarista'

# Ensures TerminAttr is leveraging the token file instead of the ingestauth key (deprecated, will be fixed in upcoming AVD release)
custom_structured_configuration_daemon_terminattr: 
  cvauth:
    method: token
    key: null
    token_file: "/tmp/token"

# sFlow configuration
sflow:
  sample: 1
  dangerous: true
  # Enable CloudVision Flow Tracker
  destinations:
    127.0.0.1:
  source_interface: Loopback0
  run: true


# OOB Management network default gateway.
mgmt_interface: Management1
mgmt_interface_vrf: MGMT
mgmt_gateway: 10.31.100.1

# dns servers.
name_servers:
  - 100.127.255.118
  - 8.8.8.8
  - 8.8.4.4

# NTP Servers IP or DNS name, first NTP server will be prefered, and sourced from Managment VRF
custom_structured_configuration_ntp:
  local_interface:
    name: Management1
    vrf: MGMT
  servers:
  - name: 0.nl.pool.ntp.org
    preferred: true
    vrf: MGMT
  - name: 1.nl.pool.ntp.org
    vrf: MGMT

#These following 2 structures are to allow the validation connectivity to the devices
custom_structured_configuration_management_api_http:
  https_ssl_profile: SSL_PROF1
  enable_https: true
  default_services: true
  enable_vrfs:
    MGMT: 

custom_structured_configuration_management_security:
 ssl_profiles:
   - name: SSL_PROF1
     tls_versions: 1.2
     certificate:
       file: capi.pem
       key: capikey.pem

#This is to allow scp directly to the devices
custom_structured_configuration_aaa_authorization:
  exec:
    default: local

##DCI SECTION: provides 2 links between DC1 and DC2 for underlay connectivity

l3_edge:
  p2p_links_ip_pools:
    dci_pool: 10.254.0.0/24
  p2p_links_profiles:
    dci_profile:
      # AS Numbers for BGP | Required with bgp peering
      as: [ 65101, 65201 ]
      # Add this interface to underlay routing protocol | Optional
      include_in_underlay_protocol: true
      # IP Pool defined under p2p_links_ip_pools. A /31 will be taken from the pool per P2P link | Optional (Requires ip_pool or subnet or ip)
      ip_pool: dci_pool

  p2p_links:
    - id: 1
      profile: dci_profile
      # Nodes where this link should be configured | Required
      nodes: [ DC1-LEAF1B, DC2-LEAF1A ]
      # Interfaces where this link should be configured | Required
      interfaces: [ Ethernet5, Ethernet5]
    - id: 2
      profile: dci_profile
      # Nodes where this link should be configured | Required
      nodes: [ DC1-LEAF1B, DC2-LEAF1A ]
      # Interfaces where this link should be configured | Required
      interfaces: [ Ethernet6, Ethernet6 ]

#The following is for the report-validate_state role:

validation_mode_loose: false

validation_role:
  xcvr_own_manufacturers:
    - Manufacturer 1
    - Manufacturer 2
  pwr_supply_states:
    - ok
    - notInserted
  fan_states:
    - ok
    - notInserted



port_profiles:
  TENANT_A_v10-11:
    mode: trunk
    vlans: "10-11"
  TENANT_A_v10:
    mode: access
    vlans: "10"
  TENANT_A_v11:
    mode: access
    vlans: "11"    
  TENANT_A_WEB_Zone:
    mode: access
    vlans: "20"    
  TENANT_A_FIREWALL:
    mode: trunk
    vlans: "10,11"  
  ROUTER:
    mode: trunk
    vlans: "300-400"

  

  
